FROM alpine:3.19 as alpine
RUN apk add -U --no-cache ca-certificates

FROM alpine:3.19
ENV GODEBUG netdns=go

COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ADD release/linux/arm64/drone-helm3-push /bin/
ENTRYPOINT ["/bin/drone-helm3-push"]
