# escape=`
FROM plugins/base:windows-ltsc2022-amd64@sha256:5e4fde61da26657b7784702b3d0854e171b3f209913533fd120322cd2dfa994e

LABEL maintainer="Jim Sheldon <jim.sheldon@harness.io>" `
  org.label-schema.name="Drone GitHub Release" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/plugin.exe C:/bin/drone-helm3-push.exe
ENTRYPOINT [ "C:\\bin\\drone-helm3-push.exe" ]